/*
 * generated by Xtext
 */
package org.yazgel.hermes.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.yazgel.hermes.xtext.ui.internal.HermesActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HermesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return HermesActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return HermesActivator.getInstance().getInjector(HermesActivator.ORG_YAZGEL_HERMES_XTEXT_HERMES);
	}
	
}
