/*
* generated by Xtext
*/
package org.yazgel.hermes.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class HermesUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.yazgel.hermes.xtext.ui.internal.HermesActivator.getInstance().getInjector("org.yazgel.hermes.xtext.Hermes");
	}
	
}
