/*
* generated by Xtext
*/
package org.yazgel.hermes.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.yazgel.hermes.xtext.services.HermesGrammarAccess;

public class HermesParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private HermesGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.yazgel.hermes.xtext.parser.antlr.internal.InternalHermesParser createParser(XtextTokenStream stream) {
		return new org.yazgel.hermes.xtext.parser.antlr.internal.InternalHermesParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Package";
	}
	
	public HermesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(HermesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
