/*
 * generated by Xtext
 */
package org.yazgel.hermes.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HermesRuntimeModule extends org.yazgel.hermes.xtext.AbstractHermesRuntimeModule {

}
