/*
 * generated by Xtext
 */
package org.yazgel.hermes.xtext.ui.contentassist

import org.yazgel.hermes.xtext.ui.contentassist.AbstractHermesProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class HermesProposalProvider extends AbstractHermesProposalProvider {
}
