/*
 * generated by Xtext
 */
package org.yazgel.hermes.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HermesUiModule extends org.yazgel.hermes.xtext.ui.AbstractHermesUiModule {
	public HermesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
