/*
 * generated by Xtext
 */
package org.yazgel.hermes.xtext.validation

import org.eclipse.xtext.validation.Check
import org.yazgel.hermes.Entity
import org.yazgel.hermes.HermesPackage

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class HermesValidator extends AbstractHermesValidator {

	@Check
	def checkNoCycleInEntityHierarchy(Entity entity) {
		if (entity.superEntity == null)
			return // nothing to check
		val visitedEntities = <Entity>newHashSet()
		visitedEntities.add(entity)
		var current = entity.superEntity
		while (current != null) {
			if (visitedEntities.contains(current)) {
				error("cycle in hierarchy of entity '" + current.name + "'",
					HermesPackage::eINSTANCE.entity_SuperEntity)
				return
			}
			visitedEntities.add(current)
			current = current.superEntity
		}
	}
}
